# Generated by Django 5.2.1 on 2025-06-10 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='time_read',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
