# Generated by Django 5.2.1 on 2025-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_time_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time_read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
